inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Style/Copyright:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*'

AllCops:
  EnabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
